# Generated by Django 3.2 on 2022-10-03 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userfavourites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFavourites',
        ),
    ]
