# Generated by Django 3.2 on 2022-10-03 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamereview',
            name='rating',
        ),
    ]
